
spring:
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.25.197.159:3306/cloud
    username: root
    password: root1989128
  jpa:
    database: mysql
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 300
server:
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8887/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
#文件上传地址
comm:
  upload:
    root: D:\\test\\
rocketMq:
  nameSrv:
    addr: 118.25.197.159
    port: 9876