
spring:
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=utf-8
    username: root
    password: ENC(S5oDA0S6hWdD+6eeaYAjTH01Cu74Epsp)
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  main:
    allow-bean-definition-overriding: true
server:
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8887/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
#加密盐
jasypt:
  encryptor:
    password: haha
#文件上传地址
comm:
  upload:
    root: /Users/lfd/Pictures/test
rocketMq:
  nameSrv:
    addr: 118.25.197.159
    port: 9876
